# Generated by Django 5.2.3 on 2025-06-30 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alunos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'categoria': 'estudante'}, related_name='cursos_matriculados', to=settings.AUTH_USER_MODEL, verbose_name='Alunos Matriculados'),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(blank=True, limit_choices_to={'categoria': 'professor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável'),
        ),
    ]
