# Generated by Django 5.2.3 on 2025-07-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_alunos_alter_course_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('conta', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=50)),
                ('instrucoes_extra', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/imagens/'),
        ),
        migrations.AddField(
            model_name='course',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
