# Generated by Django 5.2.3 on 2025-07-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_dadospagamento_course_imagem_course_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoPrecoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.IntegerField(choices=[(1, '1x por semana'), (2, '2x por semana'), (3, '3x por semana')])),
                ('duracao', models.CharField(choices=[('30min', '30 minutos'), ('1h', '1 hora')], max_length=10)),
                ('preco', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_preco', to='courses.course')),
            ],
        ),
    ]
