# Generated by Django 5.2.3 on 2025-07-07 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_planoprecocurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoprecocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='planoprecocurso',
            name='frequencia',
            field=models.CharField(choices=[('1x', '1 vez por semana'), ('2x', '2 vezes por semana'), ('3x', '3 vezes por semana')], max_length=10),
        ),
        migrations.AlterField(
            model_name='planoprecocurso',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
