# Generated by Django 5.2.3 on 2025-07-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_planoprecocurso_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preco',
        ),
    ]
