# Generated by Django 5.2.3 on 2025-06-21 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermedio', 'Intermédio'), ('avancado', 'Avançado'), ('fluente', 'Fluente')], max_length=20, verbose_name='Nível')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alunos', models.ManyToManyField(blank=True, limit_choices_to={'tipo_acesso': 'padrao'}, related_name='salas_matriculadas', to=settings.AUTH_USER_MODEL, verbose_name='Alunos Matriculados')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Curso')),
                ('professor', models.ForeignKey(limit_choices_to={'tipo_acesso': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável')),
            ],
        ),
    ]
