# Generated by Django 5.2.3 on 2025-06-21 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='alunos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tipo_acesso': 'padrao'}, related_name='salas_matriculadas', to=settings.AUTH_USER_MODEL, verbose_name='Alunos na Sala'),
        ),
    ]
