# Generated by Django 5.2.3 on 2025-07-01 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_classroom_alunos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='salas_matriculadas', to=settings.AUTH_USER_MODEL, verbose_name='Alunos na Sala'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'categoria': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Professor Responsável'),
        ),
    ]
