# Generated by Django 5.2.3 on 2025-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_alunos_alter_classroom_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='nivel',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('pré-intermédio', 'Pré-Intermédio'), ('intermedio', 'Intermédio'), ('avancado', 'Avançado')], max_length=20, verbose_name='Nível'),
        ),
    ]
