# Generated by Django 5.2.3 on 2025-07-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(max_length=100)),
                ('titular_conta', models.CharField(max_length=100)),
                ('numero_conta', models.CharField(max_length=30)),
                ('iban', models.CharField(max_length=40)),
                ('swift', models.CharField(blank=True, max_length=20, null=True)),
                ('instrucao_extra', models.TextField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
