# Generated by Django 5.2.3 on 2025-07-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivelamento', '0002_quizpergunta_quizresposta_resultadoteste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidomatricula',
            name='avaliado_pagamento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidomatricula',
            name='comprovativo',
            field=models.FileField(blank=True, null=True, upload_to='pagamentos/comprovativos/'),
        ),
        migrations.AddField(
            model_name='pedidomatricula',
            name='pagamento_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
