# Generated by Django 5.2.3 on 2025-07-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivelamento', '0003_pedidomatricula_avaliado_pagamento_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivelamento.quizpergunta')),
                ('resposta_escolhida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nivelamento.quizresposta')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_aluno', to='nivelamento.resultadoteste')),
            ],
        ),
    ]
