# Generated by Django 5.2.3 on 2025-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivelamento', '0005_pedidomatricula_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpergunta',
            name='nivel',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('pré-intermédio', 'Pré-Intermédio'), ('intermedio', 'Intermédio'), ('avancado', 'Avançado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resultadoteste',
            name='nivel_atribuido',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('pré-intermédio', 'Pré-Intermédio'), ('intermedio', 'Intermédio'), ('avancado', 'Avançado')], max_length=20),
        ),
    ]
