# Generated by Django 5.2.3 on 2025-07-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicacao', '0002_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoprofessor',
            name='nota',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')]),
        ),
    ]
